### PR TITLE
Feature/macosx

### PR DESCRIPTION
**Pull request by sepanyol**
changed osx specific changes and window metrics

### CODE REVIEW

**Comment by mrbesen** [comment]
Looks great so far, but i have no way to test it on a mac-computer. Did you tested it?
I am going to test it on windows and ubuntu before merging. Thank you for your Help!

**Comment by sepanyol** [comment]
@mrbesen , yes indeed. I've tested it on Mac OSX because that's the platform I'm using ;-) 

Do you need any screenshots of proof?

**Comment by mrbesen** [comment]
Yes, that would be helpful, i wonder whether the program looks in OSX as intended.

**Comment by mrbesen** [comment]
merged at ee755219d441a9f2a7b045c5a77b07f08c3906ef to dev branch
Thank you @dcballs , for your help.

**Pull request closed without merging**
